/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.przeliczaniki;

import java.io.*;
import java.util.Scanner;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author sawic
 */

public class Przeliczniki extends javax.swing.JFrame {

    /**
     * Creates new form Przeliczniki
     */
    public Przeliczniki() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTemp = new javax.swing.ButtonGroup();
        buttonGroupMiara = new javax.swing.ButtonGroup();
        js_jPanel = new javax.swing.JPanel();
        js_jTabbedPaneMiara = new javax.swing.JTabbedPane();
        js_jPanelTemp = new javax.swing.JPanel();
        js_jLabelWartoscM = new javax.swing.JLabel();
        js_jTextFieldWartoscT = new javax.swing.JTextField();
        js_jLabelDzialanieM = new javax.swing.JLabel();
        js_jLabelWynik = new javax.swing.JLabel();
        js_jRadioButtonKT = new javax.swing.JRadioButton();
        js_jRadioButtonCT = new javax.swing.JRadioButton();
        js_jRadioButtonFT = new javax.swing.JRadioButton();
        js_jButtonOblicz2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        js_jTextFieldWynik2 = new javax.swing.JTextField();
        js_jLabelDomyslnaT = new javax.swing.JLabel();
        js_jPanelMiara = new javax.swing.JPanel();
        js_jLabelWartoscT = new javax.swing.JLabel();
        js_jTextFieldWartoscMiara = new javax.swing.JTextField();
        js_jLabelWynikT = new javax.swing.JLabel();
        js_jButton = new javax.swing.JButton();
        js_jLabelUrWynik = new javax.swing.JLabel();
        js_jTextFieldWynik = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        js_jRadioButtonMMM = new javax.swing.JRadioButton();
        js_jRadioButtonCMM = new javax.swing.JRadioButton();
        js_jRadioButtonDMM = new javax.swing.JRadioButton();
        js_jRadioButtonMM = new javax.swing.JRadioButton();
        js_jRadioButtonKMM = new javax.swing.JRadioButton();
        js_jLabelDomyslnaM = new javax.swing.JLabel();
        js_jLabelPrzelicznik = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        js_jMenuPlik = new javax.swing.JMenu();
        js_jMenuItemHis = new javax.swing.JMenuItem();
        js_jMenuItemZP = new javax.swing.JMenuItem();
        js_jMenuOP = new javax.swing.JMenu();
        js_jMenuItemOP = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        js_jPanel.setBackground(new java.awt.Color(51, 51, 51));

        js_jTabbedPaneMiara.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                js_jTabbedPaneMiaraStateChanged(evt);
            }
        });

        js_jPanelTemp.setBackground(new java.awt.Color(0, 0, 0));

        js_jLabelWartoscM.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        js_jLabelWartoscM.setForeground(new java.awt.Color(255, 255, 255));
        js_jLabelWartoscM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        js_jLabelWartoscM.setText("Podaj wartosc:");

        js_jLabelDzialanieM.setBackground(new java.awt.Color(0, 0, 0));
        js_jLabelDzialanieM.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        js_jLabelDzialanieM.setForeground(new java.awt.Color(255, 255, 255));
        js_jLabelDzialanieM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        js_jLabelDzialanieM.setText("Wybierz działanie:");

        js_jLabelWynik.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        js_jLabelWynik.setForeground(new java.awt.Color(255, 255, 255));
        js_jLabelWynik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        js_jLabelWynik.setText("Wynik:");

        js_jRadioButtonKT.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTemp.add(js_jRadioButtonKT);
        js_jRadioButtonKT.setForeground(new java.awt.Color(255, 255, 255));
        js_jRadioButtonKT.setText("Kelwin (k)");

        js_jRadioButtonCT.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTemp.add(js_jRadioButtonCT);
        js_jRadioButtonCT.setForeground(new java.awt.Color(255, 255, 255));
        js_jRadioButtonCT.setText("Celsjusz (°C)");

        js_jRadioButtonFT.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTemp.add(js_jRadioButtonFT);
        js_jRadioButtonFT.setForeground(new java.awt.Color(255, 255, 255));
        js_jRadioButtonFT.setText("Fahrenheit (°F)");

        js_jButtonOblicz2.setText("Oblicz");
        js_jButtonOblicz2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                js_jButtonOblicz2ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Twój Wynik:");

        js_jLabelDomyslnaT.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        js_jLabelDomyslnaT.setForeground(new java.awt.Color(255, 255, 255));
        js_jLabelDomyslnaT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        js_jLabelDomyslnaT.setText("Wartosc domyslna: Celsjusz");

        javax.swing.GroupLayout js_jPanelTempLayout = new javax.swing.GroupLayout(js_jPanelTemp);
        js_jPanelTemp.setLayout(js_jPanelTempLayout);
        js_jPanelTempLayout.setHorizontalGroup(
            js_jPanelTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(js_jLabelDzialanieM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(js_jLabelWynik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(js_jPanelTempLayout.createSequentialGroup()
                .addGroup(js_jPanelTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(js_jPanelTempLayout.createSequentialGroup()
                        .addComponent(js_jLabelWartoscM, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(js_jTextFieldWartoscT))
                    .addGroup(js_jPanelTempLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(js_jRadioButtonKT)
                        .addGap(18, 18, 18)
                        .addComponent(js_jRadioButtonCT)
                        .addGap(18, 18, 18)
                        .addComponent(js_jRadioButtonFT)
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, js_jPanelTempLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(js_jButtonOblicz2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(js_jPanelTempLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(js_jTextFieldWynik2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, js_jPanelTempLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(js_jLabelDomyslnaT, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        js_jPanelTempLayout.setVerticalGroup(
            js_jPanelTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(js_jPanelTempLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(js_jLabelDomyslnaT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(js_jPanelTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_jLabelWartoscM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_jTextFieldWartoscT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(js_jLabelDzialanieM, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(js_jPanelTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_jRadioButtonKT)
                    .addComponent(js_jRadioButtonCT)
                    .addComponent(js_jRadioButtonFT))
                .addGap(27, 27, 27)
                .addComponent(js_jButtonOblicz2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(js_jLabelWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(js_jPanelTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_jTextFieldWynik2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        js_jTabbedPaneMiara.addTab("Temperatura", js_jPanelTemp);

        js_jPanelMiara.setBackground(new java.awt.Color(0, 0, 0));

        js_jLabelWartoscT.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        js_jLabelWartoscT.setForeground(new java.awt.Color(255, 255, 255));
        js_jLabelWartoscT.setText("Podaj wartosc:");

        js_jTextFieldWartoscMiara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                js_jTextFieldWartoscMiaraActionPerformed(evt);
            }
        });

        js_jLabelWynikT.setBackground(new java.awt.Color(0, 0, 0));
        js_jLabelWynikT.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        js_jLabelWynikT.setForeground(new java.awt.Color(255, 255, 255));
        js_jLabelWynikT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        js_jLabelWynikT.setText("Wynik:");

        js_jButton.setText("Oblicz");
        js_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                js_jButtonActionPerformed(evt);
            }
        });

        js_jLabelUrWynik.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        js_jLabelUrWynik.setForeground(new java.awt.Color(255, 255, 255));
        js_jLabelUrWynik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        js_jLabelUrWynik.setText("Twój wynik:");

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Wybierz działanie:");

        js_jRadioButtonMMM.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupMiara.add(js_jRadioButtonMMM);
        js_jRadioButtonMMM.setForeground(new java.awt.Color(255, 255, 255));
        js_jRadioButtonMMM.setText("mm");
        js_jRadioButtonMMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                js_jRadioButtonMMMActionPerformed(evt);
            }
        });

        js_jRadioButtonCMM.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupMiara.add(js_jRadioButtonCMM);
        js_jRadioButtonCMM.setForeground(new java.awt.Color(255, 255, 255));
        js_jRadioButtonCMM.setText("cm");

        js_jRadioButtonDMM.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupMiara.add(js_jRadioButtonDMM);
        js_jRadioButtonDMM.setForeground(new java.awt.Color(255, 255, 255));
        js_jRadioButtonDMM.setText("dm");

        js_jRadioButtonMM.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupMiara.add(js_jRadioButtonMM);
        js_jRadioButtonMM.setForeground(new java.awt.Color(255, 255, 255));
        js_jRadioButtonMM.setText("m");

        js_jRadioButtonKMM.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupMiara.add(js_jRadioButtonKMM);
        js_jRadioButtonKMM.setForeground(new java.awt.Color(255, 255, 255));
        js_jRadioButtonKMM.setText("km");

        js_jLabelDomyslnaM.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        js_jLabelDomyslnaM.setForeground(new java.awt.Color(255, 255, 255));
        js_jLabelDomyslnaM.setText("Wartosc domyslna: mm");

        javax.swing.GroupLayout js_jPanelMiaraLayout = new javax.swing.GroupLayout(js_jPanelMiara);
        js_jPanelMiara.setLayout(js_jPanelMiaraLayout);
        js_jPanelMiaraLayout.setHorizontalGroup(
            js_jPanelMiaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(js_jLabelWynikT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(js_jPanelMiaraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(js_jLabelWartoscT, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(js_jPanelMiaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(js_jPanelMiaraLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(js_jTextFieldWartoscMiara)
                        .addContainerGap())
                    .addGroup(js_jPanelMiaraLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(js_jLabelDomyslnaM, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(49, Short.MAX_VALUE))))
            .addGroup(js_jPanelMiaraLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(js_jLabelUrWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(js_jTextFieldWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(js_jPanelMiaraLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(js_jRadioButtonMMM)
                .addGap(18, 18, 18)
                .addComponent(js_jRadioButtonCMM)
                .addGap(18, 18, 18)
                .addComponent(js_jRadioButtonDMM)
                .addGap(18, 18, 18)
                .addComponent(js_jRadioButtonMM)
                .addGap(18, 18, 18)
                .addComponent(js_jRadioButtonKMM)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, js_jPanelMiaraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(js_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        js_jPanelMiaraLayout.setVerticalGroup(
            js_jPanelMiaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(js_jPanelMiaraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(js_jPanelMiaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(js_jLabelWartoscT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(js_jPanelMiaraLayout.createSequentialGroup()
                        .addComponent(js_jLabelDomyslnaM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(js_jTextFieldWartoscMiara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(js_jPanelMiaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_jRadioButtonDMM)
                    .addComponent(js_jRadioButtonMM)
                    .addComponent(js_jRadioButtonKMM)
                    .addComponent(js_jRadioButtonCMM)
                    .addComponent(js_jRadioButtonMMM))
                .addGap(18, 18, 18)
                .addComponent(js_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(js_jLabelWynikT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(js_jPanelMiaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_jLabelUrWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_jTextFieldWynik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        js_jTabbedPaneMiara.addTab("Miara", js_jPanelMiara);

        js_jLabelPrzelicznik.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        js_jLabelPrzelicznik.setForeground(new java.awt.Color(255, 255, 255));
        js_jLabelPrzelicznik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        js_jLabelPrzelicznik.setText("Przelicznik Jednostek");

        javax.swing.GroupLayout js_jPanelLayout = new javax.swing.GroupLayout(js_jPanel);
        js_jPanel.setLayout(js_jPanelLayout);
        js_jPanelLayout.setHorizontalGroup(
            js_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(js_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(js_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(js_jLabelPrzelicznik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, js_jPanelLayout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addComponent(js_jTabbedPaneMiara, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        js_jPanelLayout.setVerticalGroup(
            js_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, js_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(js_jLabelPrzelicznik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(js_jTabbedPaneMiara, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        js_jMenuPlik.setText("Plik");

        js_jMenuItemHis.setText("Pokaż historię");
        js_jMenuItemHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                js_jMenuItemHisActionPerformed(evt);
            }
        });
        js_jMenuPlik.add(js_jMenuItemHis);

        js_jMenuItemZP.setText("Zamknij program");
        js_jMenuItemZP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                js_jMenuItemZPActionPerformed(evt);
            }
        });
        js_jMenuPlik.add(js_jMenuItemZP);

        jMenuBar1.add(js_jMenuPlik);

        js_jMenuOP.setText("O programie");

        js_jMenuItemOP.setText("O programie");
        js_jMenuItemOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                js_jMenuItemOPActionPerformed(evt);
            }
        });
        js_jMenuOP.add(js_jMenuItemOP);

        jMenuBar1.add(js_jMenuOP);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(js_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(js_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void js_jTabbedPaneMiaraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_js_jTabbedPaneMiaraStateChanged
        
    }//GEN-LAST:event_js_jTabbedPaneMiaraStateChanged

    private void js_jTextFieldWartoscMiaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_js_jTextFieldWartoscMiaraActionPerformed

    }//GEN-LAST:event_js_jTextFieldWartoscMiaraActionPerformed

    private void js_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_js_jButtonActionPerformed
        Miara();
        MiaraZapis();
    }//GEN-LAST:event_js_jButtonActionPerformed

    private void js_jRadioButtonMMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_js_jRadioButtonMMMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_js_jRadioButtonMMMActionPerformed

    private void js_jButtonOblicz2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_js_jButtonOblicz2ActionPerformed
        Temperatura();
        TemperaturaZapis();
    }//GEN-LAST:event_js_jButtonOblicz2ActionPerformed

    private void js_jMenuItemZPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_js_jMenuItemZPActionPerformed
        System.exit(0);
    }//GEN-LAST:event_js_jMenuItemZPActionPerformed

    private void js_jMenuItemOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_js_jMenuItemOPActionPerformed
      JButton button = new JButton();
      button.setIcon(null);      
      JOptionPane.showMessageDialog(this,"<html>Program służący do przeliczania jednostek<html>");

    }//GEN-LAST:event_js_jMenuItemOPActionPerformed

    private void js_jMenuItemHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_js_jMenuItemHisActionPerformed
        Historia();
        button.setIcon(null);
    }//GEN-LAST:event_js_jMenuItemHisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Przeliczniki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Przeliczniki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Przeliczniki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Przeliczniki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Przeliczniki().setVisible(true);
            }
        });
    }
    private void Miara(){
        String uzyt = js_jTextFieldWartoscMiara.getText();
        Double nw = Double.parseDouble(uzyt);  
        
        String mm=Double.toString(nw);
        String cm=Double.toString(nw/10);
        String dm=Double.toString(nw/100);
        String m=Double.toString(nw/1000);
        String km=Double.toString(nw/10000);
        if(js_jRadioButtonMMM.isSelected()){
            js_jTextFieldWynik.setText(""+mm+"mm");
            
        }else if(js_jRadioButtonCMM.isSelected()){
            js_jTextFieldWynik.setText(""+cm+"cm");
            
        }else if(js_jRadioButtonDMM.isSelected()){
            js_jTextFieldWynik.setText(""+dm+"dm");
            
        }else if(js_jRadioButtonMM.isSelected()){
            js_jTextFieldWynik.setText(""+m+"m");
            
        }else if(js_jRadioButtonKMM.isSelected()){
            js_jTextFieldWynik.setText(""+km+"km");
        }
    }
    private void Temperatura(){
        String Uzyt = js_jTextFieldWartoscT.getText();
        Double nw = Double.parseDouble(Uzyt);
        
        String c=Double.toString(nw);
        String k=Double.toString(nw+273);
        String f=Double.toString((nw*9/5)+32);        
        if(js_jRadioButtonKT.isSelected()){
            js_jTextFieldWynik2.setText(""+k+"K");
            
        }else if(js_jRadioButtonCT.isSelected()){
            js_jTextFieldWynik2.setText(""+c+"°C");
            
        }else if(js_jRadioButtonFT.isSelected()){
            js_jTextFieldWynik2.setText(""+f+"°F");
            
        }
    }
        private void TemperaturaZapis(){
        File f = new File("zapis.txt");
        FileWriter fw;
        try {
            fw = new FileWriter(f,true);
            fw.append("t;"+js_jTextFieldWartoscT.getText()+"°C;"+js_jTextFieldWynik2.getText()+"\n");
            fw.close();
        } catch (IOException e) {
            System.out.println("BLAD: "+e.toString());
        }
    }
    
    private void MiaraZapis(){
        File f = new File("zapis.txt");
        FileWriter fw;
        try {
            fw = new FileWriter(f,true);
            fw.append("o;"+js_jTextFieldWartoscMiara.getText()+"cm"+js_jTextFieldWynik.getText()+"\n");
            fw.close();
        } catch (IOException ex) {
            System.out.println(ex.toString());
        }
    }
    private void Historia(){
        JFileChooser js = new JFileChooser();
        File f = new File("zapis.txt");
        try {
            String Tekst = "";
            Scanner sc = new Scanner(f);
            while(sc.hasNext()){
                Tekst = Tekst+"\n"+sc.nextLine();
            }
            JOptionPane.showMessageDialog(this,Tekst);
        }
        catch(FileNotFoundException ex) {
            System.out.println(ex.toString());
        }
    }
    File Save = new File("Zapis.txt");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupMiara;
    private javax.swing.ButtonGroup buttonGroupTemp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton js_jButton;
    private javax.swing.JButton js_jButtonOblicz2;
    private javax.swing.JLabel js_jLabelDomyslnaM;
    private javax.swing.JLabel js_jLabelDomyslnaT;
    private javax.swing.JLabel js_jLabelDzialanieM;
    private javax.swing.JLabel js_jLabelPrzelicznik;
    private javax.swing.JLabel js_jLabelUrWynik;
    private javax.swing.JLabel js_jLabelWartoscM;
    private javax.swing.JLabel js_jLabelWartoscT;
    private javax.swing.JLabel js_jLabelWynik;
    private javax.swing.JLabel js_jLabelWynikT;
    private javax.swing.JMenuItem js_jMenuItemHis;
    private javax.swing.JMenuItem js_jMenuItemOP;
    private javax.swing.JMenuItem js_jMenuItemZP;
    private javax.swing.JMenu js_jMenuOP;
    private javax.swing.JMenu js_jMenuPlik;
    private javax.swing.JPanel js_jPanel;
    private javax.swing.JPanel js_jPanelMiara;
    private javax.swing.JPanel js_jPanelTemp;
    private javax.swing.JRadioButton js_jRadioButtonCMM;
    private javax.swing.JRadioButton js_jRadioButtonCT;
    private javax.swing.JRadioButton js_jRadioButtonDMM;
    private javax.swing.JRadioButton js_jRadioButtonFT;
    private javax.swing.JRadioButton js_jRadioButtonKMM;
    private javax.swing.JRadioButton js_jRadioButtonKT;
    private javax.swing.JRadioButton js_jRadioButtonMM;
    private javax.swing.JRadioButton js_jRadioButtonMMM;
    private javax.swing.JTabbedPane js_jTabbedPaneMiara;
    private javax.swing.JTextField js_jTextFieldWartoscMiara;
    private javax.swing.JTextField js_jTextFieldWartoscT;
    private javax.swing.JTextField js_jTextFieldWynik;
    private javax.swing.JTextField js_jTextFieldWynik2;
    // End of variables declaration//GEN-END:variables
}

