/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.kartkowka;

/**
 *
 * @author sawic
 */
public class karkowka extends javax.swing.JFrame {

    /**
     * Creates new form karkowka
     */
    public karkowka() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        js_jMenuNew = new javax.swing.JMenu();
        jMenuItemNew = new javax.swing.JMenuItem();
        js_jSeparator1 = new javax.swing.JPopupMenu.Separator();
        js_jMenuOpen = new javax.swing.JMenuItem();
        js_jMenuOtworzPoprzedni = new javax.swing.JMenu();
        Js_MenuOtworzZaPomoca = new javax.swing.JMenu();
        js_jSeparator3 = new javax.swing.JPopupMenu.Separator();
        js_jMenuItemSave = new javax.swing.JMenuItem();
        js_jMenuItemSaveUs = new javax.swing.JMenuItem();
        js_jMenuSaveCode = new javax.swing.JMenu();
        js_jMenuItemSaveCopy = new javax.swing.JMenuItem();
        js_jMenuItemSaveAll = new javax.swing.JMenuItem();
        js_jSeparator4 = new javax.swing.JPopupMenu.Separator();
        js_jMenuItemLoad = new javax.swing.JMenuItem();
        js_jMenuItemLoadAll = new javax.swing.JMenuItem();
        js_jMenuItemPrint = new javax.swing.JMenuItem();
        js_jMenuItemPrintPod = new javax.swing.JMenuItem();
        js_jSeparator5 = new javax.swing.JPopupMenu.Separator();
        js_jMenuItemExport = new javax.swing.JMenuItem();
        js_jSeparator6 = new javax.swing.JPopupMenu.Separator();
        js_jMenuItemChangeName = new javax.swing.JMenuItem();
        js_jMenuItemDelete = new javax.swing.JMenuItem();
        js_jMenuItemPorownaj = new javax.swing.JMenuItem();
        js_jSeparator7 = new javax.swing.JPopupMenu.Separator();
        js_jMenuItemCopyURL = new javax.swing.JMenuItem();
        js_jMenuItemOpenFolder = new javax.swing.JMenuItem();
        js_jMenuItemProperties = new javax.swing.JMenuItem();
        js_jSeparator2 = new javax.swing.JPopupMenu.Separator();
        js_jMenuItemClose = new javax.swing.JMenuItem();
        js_jMenuItemCloseOther = new javax.swing.JMenuItem();
        js_jMenuItemCloseAll = new javax.swing.JMenuItem();
        js_jMenuItemCloseDel = new javax.swing.JMenuItem();
        js_jSeparator8 = new javax.swing.JPopupMenu.Separator();
        js_jMenuItemFinish = new javax.swing.JMenuItem();
        js_jMenuEdit = new javax.swing.JMenu();
        js_jMenuWidok = new javax.swing.JMenu();
        js_jMenuProject = new javax.swing.JMenu();
        js_jMenuZakladki = new javax.swing.JMenu();
        js_jMenuSesje = new javax.swing.JMenu();
        js_jMenuNarzedzia = new javax.swing.JMenu();
        js_jMenuUstawienia = new javax.swing.JMenu();
        js_jMenuPomoc = new javax.swing.JMenu();

        jMenu10.setText("File");
        jMenuBar2.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar2.add(jMenu11);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        js_jMenuNew.setText("Plik");

        jMenuItemNew.setText("Nowy");
        js_jMenuNew.add(jMenuItemNew);
        js_jMenuNew.add(js_jSeparator1);

        js_jMenuOpen.setText("Otwórz...");
        js_jMenuOpen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                js_jMenuOpenStateChanged(evt);
            }
        });
        js_jMenuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                js_jMenuOpenActionPerformed(evt);
            }
        });
        js_jMenuNew.add(js_jMenuOpen);

        js_jMenuOtworzPoprzedni.setText("Otwórz poprzedni");
        js_jMenuNew.add(js_jMenuOtworzPoprzedni);

        Js_MenuOtworzZaPomoca.setBackground(new java.awt.Color(102, 102, 102));
        Js_MenuOtworzZaPomoca.setForeground(new java.awt.Color(102, 102, 102));
        Js_MenuOtworzZaPomoca.setText("Otwórz za pomocą");
        js_jMenuNew.add(Js_MenuOtworzZaPomoca);
        js_jMenuNew.add(js_jSeparator3);

        js_jMenuItemSave.setText("Zapisz");
        js_jMenuNew.add(js_jMenuItemSave);

        js_jMenuItemSaveUs.setText("Zapisz Jako...");
        js_jMenuItemSaveUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                js_jMenuItemSaveUsActionPerformed(evt);
            }
        });
        js_jMenuNew.add(js_jMenuItemSaveUs);

        js_jMenuSaveCode.setText("Zapisz jako z kodowaniem...");
        js_jMenuNew.add(js_jMenuSaveCode);

        js_jMenuItemSaveCopy.setText("Zapisz kopię jako...");
        js_jMenuNew.add(js_jMenuItemSaveCopy);

        js_jMenuItemSaveAll.setText("Zapisz wszystko");
        js_jMenuNew.add(js_jMenuItemSaveAll);
        js_jMenuNew.add(js_jSeparator4);

        js_jMenuItemLoad.setText("Wczytaj ponownie");
        js_jMenuItemLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                js_jMenuItemLoadActionPerformed(evt);
            }
        });
        js_jMenuNew.add(js_jMenuItemLoad);

        js_jMenuItemLoadAll.setText("Wczytaj ponownie wszystko");
        js_jMenuItemLoadAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                js_jMenuItemLoadAllActionPerformed(evt);
            }
        });
        js_jMenuNew.add(js_jMenuItemLoadAll);

        js_jMenuItemPrint.setText("Drukuj...");
        js_jMenuNew.add(js_jMenuItemPrint);

        js_jMenuItemPrintPod.setText("Podgląd wydruku");
        js_jMenuNew.add(js_jMenuItemPrintPod);
        js_jMenuNew.add(js_jSeparator5);

        js_jMenuItemExport.setText("Eksportuj jako HTML...");
        js_jMenuNew.add(js_jMenuItemExport);
        js_jMenuNew.add(js_jSeparator6);

        js_jMenuItemChangeName.setForeground(new java.awt.Color(102, 102, 102));
        js_jMenuItemChangeName.setText("Zmień nazwę...");
        js_jMenuNew.add(js_jMenuItemChangeName);

        js_jMenuItemDelete.setForeground(new java.awt.Color(102, 102, 102));
        js_jMenuItemDelete.setText("Usuń");
        js_jMenuNew.add(js_jMenuItemDelete);

        js_jMenuItemPorownaj.setText("Porównaj");
        js_jMenuNew.add(js_jMenuItemPorownaj);
        js_jMenuNew.add(js_jSeparator7);

        js_jMenuItemCopyURL.setForeground(new java.awt.Color(102, 102, 102));
        js_jMenuItemCopyURL.setText("Skopiuj ścieżke pliku");
        js_jMenuNew.add(js_jMenuItemCopyURL);

        js_jMenuItemOpenFolder.setForeground(new java.awt.Color(102, 102, 102));
        js_jMenuItemOpenFolder.setText("Otwórz katalog zawierający");
        js_jMenuNew.add(js_jMenuItemOpenFolder);

        js_jMenuItemProperties.setForeground(new java.awt.Color(102, 102, 102));
        js_jMenuItemProperties.setText("Właściwości");
        js_jMenuNew.add(js_jMenuItemProperties);
        js_jMenuNew.add(js_jSeparator2);

        js_jMenuItemClose.setText("Zamknij");
        js_jMenuNew.add(js_jMenuItemClose);

        js_jMenuItemCloseOther.setText("Zamknij inne");
        js_jMenuNew.add(js_jMenuItemCloseOther);

        js_jMenuItemCloseAll.setText("Zamknij wszystko");
        js_jMenuItemCloseAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                js_jMenuItemCloseAllActionPerformed(evt);
            }
        });
        js_jMenuNew.add(js_jMenuItemCloseAll);

        js_jMenuItemCloseDel.setText("Zamknij porzucone");
        js_jMenuNew.add(js_jMenuItemCloseDel);
        js_jMenuNew.add(js_jSeparator8);

        js_jMenuItemFinish.setText("Zakończ");
        js_jMenuNew.add(js_jMenuItemFinish);

        jMenuBar1.add(js_jMenuNew);

        js_jMenuEdit.setText("Edycja");
        jMenuBar1.add(js_jMenuEdit);

        js_jMenuWidok.setText("Widok");
        jMenuBar1.add(js_jMenuWidok);

        js_jMenuProject.setText("Projekty");
        jMenuBar1.add(js_jMenuProject);

        js_jMenuZakladki.setText("Zakładki");
        jMenuBar1.add(js_jMenuZakladki);

        js_jMenuSesje.setText("Sesje");
        jMenuBar1.add(js_jMenuSesje);

        js_jMenuNarzedzia.setText("Narzędzia");
        jMenuBar1.add(js_jMenuNarzedzia);

        js_jMenuUstawienia.setText("Ustawienia");
        jMenuBar1.add(js_jMenuUstawienia);

        js_jMenuPomoc.setText("Pomoc");
        jMenuBar1.add(js_jMenuPomoc);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void js_jMenuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_js_jMenuOpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_js_jMenuOpenActionPerformed

    private void js_jMenuOpenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_js_jMenuOpenStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_js_jMenuOpenStateChanged

    private void js_jMenuItemSaveUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_js_jMenuItemSaveUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_js_jMenuItemSaveUsActionPerformed

    private void js_jMenuItemLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_js_jMenuItemLoadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_js_jMenuItemLoadActionPerformed

    private void js_jMenuItemLoadAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_js_jMenuItemLoadAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_js_jMenuItemLoadAllActionPerformed

    private void js_jMenuItemCloseAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_js_jMenuItemCloseAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_js_jMenuItemCloseAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(karkowka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(karkowka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(karkowka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(karkowka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new karkowka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Js_MenuOtworzZaPomoca;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItemNew;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu js_jMenuEdit;
    private javax.swing.JMenuItem js_jMenuItemChangeName;
    private javax.swing.JMenuItem js_jMenuItemClose;
    private javax.swing.JMenuItem js_jMenuItemCloseAll;
    private javax.swing.JMenuItem js_jMenuItemCloseDel;
    private javax.swing.JMenuItem js_jMenuItemCloseOther;
    private javax.swing.JMenuItem js_jMenuItemCopyURL;
    private javax.swing.JMenuItem js_jMenuItemDelete;
    private javax.swing.JMenuItem js_jMenuItemExport;
    private javax.swing.JMenuItem js_jMenuItemFinish;
    private javax.swing.JMenuItem js_jMenuItemLoad;
    private javax.swing.JMenuItem js_jMenuItemLoadAll;
    private javax.swing.JMenuItem js_jMenuItemOpenFolder;
    private javax.swing.JMenuItem js_jMenuItemPorownaj;
    private javax.swing.JMenuItem js_jMenuItemPrint;
    private javax.swing.JMenuItem js_jMenuItemPrintPod;
    private javax.swing.JMenuItem js_jMenuItemProperties;
    private javax.swing.JMenuItem js_jMenuItemSave;
    private javax.swing.JMenuItem js_jMenuItemSaveAll;
    private javax.swing.JMenuItem js_jMenuItemSaveCopy;
    private javax.swing.JMenuItem js_jMenuItemSaveUs;
    private javax.swing.JMenu js_jMenuNarzedzia;
    private javax.swing.JMenu js_jMenuNew;
    private javax.swing.JMenuItem js_jMenuOpen;
    private javax.swing.JMenu js_jMenuOtworzPoprzedni;
    private javax.swing.JMenu js_jMenuPomoc;
    private javax.swing.JMenu js_jMenuProject;
    private javax.swing.JMenu js_jMenuSaveCode;
    private javax.swing.JMenu js_jMenuSesje;
    private javax.swing.JMenu js_jMenuUstawienia;
    private javax.swing.JMenu js_jMenuWidok;
    private javax.swing.JMenu js_jMenuZakladki;
    private javax.swing.JPopupMenu.Separator js_jSeparator1;
    private javax.swing.JPopupMenu.Separator js_jSeparator2;
    private javax.swing.JPopupMenu.Separator js_jSeparator3;
    private javax.swing.JPopupMenu.Separator js_jSeparator4;
    private javax.swing.JPopupMenu.Separator js_jSeparator5;
    private javax.swing.JPopupMenu.Separator js_jSeparator6;
    private javax.swing.JPopupMenu.Separator js_jSeparator7;
    private javax.swing.JPopupMenu.Separator js_jSeparator8;
    // End of variables declaration//GEN-END:variables
}
